# Generated by Django 5.2 on 2025-05-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_department_doctor_specialization_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first", "Первая категория"),
                    ("second", "Вторая категория"),
                    ("highest", "Высшая категория"),
                ],
                max_length=20,
                null=True,
                verbose_name="Категория",
            ),
        ),
    ]
