# Generated by Django 5.2 on 2025-05-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_doctor_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first", "Первая категория"),
                    ("second", "Вторая категория"),
                    ("highest", "Высшая категория"),
                ],
                default=None,
                max_length=20,
                null=True,
                verbose_name="Категория",
            ),
        ),
    ]
