# Generated by Django 5.2 on 2025-05-07 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_doctor_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientQuestionnaire",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "chronic_diseases",
                    models.TextField(
                        blank=True,
                        help_text="Описание имеющихся хронических заболеваний",
                        verbose_name="Хронические заболевания",
                    ),
                ),
                (
                    "allergies",
                    models.TextField(
                        blank=True,
                        help_text="Информация об аллергиях и возможных реакциях на препараты",
                        verbose_name="Аллергии и реакции",
                    ),
                ),
                (
                    "hereditary_diseases",
                    models.TextField(
                        blank=True,
                        help_text="Информация о предрасположенности к наследственным заболеваниям",
                        verbose_name="Наследственные заболевания",
                    ),
                ),
                (
                    "treatment_preferences",
                    models.TextField(
                        blank=True, help_text="Предпочитаемые методы лечения", verbose_name="Предпочтения в лечении"
                    ),
                ),
                (
                    "bad_habits",
                    models.TextField(
                        blank=True, help_text="Описание имеющихся вредных привычек", verbose_name="Вредные привычки"
                    ),
                ),
                (
                    "lifestyle",
                    models.TextField(
                        blank=True,
                        help_text="Описание образа жизни (питание, физическая активность и т.д.)",
                        verbose_name="Образ жизни",
                    ),
                ),
                (
                    "medications",
                    models.TextField(
                        blank=True,
                        help_text="Информация о принимаемых лекарственных препаратах",
                        verbose_name="Принимаемые препараты",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Анкета пациента",
                "verbose_name_plural": "Анкеты пациентов",
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
    ]
