# Generated by Django 5.2 on 2025-05-07 12:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_patientquestionnaire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="description",
            field=models.TextField(blank=True, help_text="Подробное описание отделения", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                help_text="Название отделения клиники", max_length=100, verbose_name="Название отделения"
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="academic_degree",
            field=models.CharField(
                choices=[
                    ("none", "Нет"),
                    ("candidate", "Кандидат медицинских наук"),
                    ("doctor", "Доктор медицинских наук"),
                ],
                default="none",
                help_text="Ученая степень врача",
                max_length=20,
                verbose_name="Ученая степень",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="category",
            field=models.CharField(
                choices=[
                    ("none", "Нет категории"),
                    ("second", "Вторая категория"),
                    ("first", "Первая категория"),
                    ("highest", "Высшая категория"),
                ],
                default="none",
                help_text="Квалификационная категория врача",
                max_length=20,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="department",
            field=models.ForeignKey(
                help_text="Отделение, в котором работает врач",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.department",
                verbose_name="Отделение",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="experience",
            field=models.PositiveIntegerField(
                help_text="Опыт работы врача в годах",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Стаж работы (лет)",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Рейтинг врача по отзывам пациентов (от 0 до 5)",
                max_digits=3,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)],
                verbose_name="Рейтинг",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="specialization",
            field=models.ForeignKey(
                help_text="Специализация врача",
                on_delete=django.db.models.deletion.PROTECT,
                to="users.specialization",
                verbose_name="Специализация",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="user",
            field=models.OneToOneField(
                help_text="Связанный пользователь системы",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="description",
            field=models.TextField(blank=True, help_text="Подробное описание специализации", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="name",
            field=models.CharField(
                help_text="Наименование врачебной специализации", max_length=100, verbose_name="Название специализации"
            ),
        ),
    ]
