# Generated by Django 5.2 on 2025-05-08 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_department_description_alter_department_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="description",
            field=models.TextField(blank=True, help_text="Подробная информация о враче", verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="photo",
            field=models.ImageField(
                blank=True, help_text="Фотография врача", null=True, upload_to="doctors/", verbose_name="Фотография"
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="user",
            field=models.OneToOneField(
                help_text="Связанный пользователь системы",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(fields=["user"], name="users_docto_user_id_1e9ebf_idx"),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(fields=["department"], name="users_docto_departm_179444_idx"),
        ),
    ]
