# Generated by Django 5.2 on 2025-05-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_doctor_description_doctor_photo_alter_doctor_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="document",
            field=models.CharField(
                blank=True,
                help_text="Паспорт или свидетельство о рождении",
                max_length=250,
                null=True,
                verbose_name="Документ",
            ),
        ),
    ]
