services:
  web:
    image: vormagic/web:latest
    build: .
    restart: unless-stopped
    command: >
      bash -c "python manage.py collectstatic  --noinput && 
      python manage.py migrate && 
      python manage.py csu && 
      gunicorn config.wsgi:application --bind 0.0.0.0:8000 --timeout 120 --workers 3 --max-requests 1000"

    volumes:
      - .:/medical_diagnostics
      - static_volume:/medical_diagnostics/staticfiles
      - media_volume:/medical_diagnostics/media
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_HOST=db
      - DJANGO_SETTINGS_MODULE=config.settings
    depends_on:
      db:
        condition: service_healthy

  db:
    image: docker.io/library/postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: docker.io/library/nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - static_volume:/medical_diagnostics/staticfiles
      - media_volume:/medical_diagnostics/media
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
