# Generated by Django 5.2 on 2025-05-06 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_department_doctor_specialization_alter_user_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "working_shift",
                    models.IntegerField(choices=[(1, "1 Смена"), (2, "2 Смена")], verbose_name="Рабочая смена"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="users.doctor",
                        verbose_name="Врач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расписание",
                "verbose_name_plural": "Расписание",
                "ordering": ["date"],
                "unique_together": {("doctor", "date")},
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Название услуги")),
                ("duration", models.DurationField(verbose_name="Длительность")),
                ("number_of_slots", models.IntegerField(editable=False, verbose_name="Количество слотов")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Стоимость")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активность")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.department", verbose_name="Отделение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "ordering": ["department", "-duration", "name"],
                "unique_together": {("name", "department")},
            },
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "number",
                    models.IntegerField(
                        choices=[
                            (1, "7:00"),
                            (2, "7:30"),
                            (3, "8:00"),
                            (4, "8:30"),
                            (5, "9:00"),
                            (6, "9:30"),
                            (7, "10:00"),
                            (8, "10:30"),
                            (9, "11:00"),
                            (10, "11:30"),
                            (11, "12:00"),
                            (12, "12:30"),
                            (13, "13:00"),
                            (14, "13:30"),
                            (15, "14:00"),
                            (16, "14:30"),
                            (17, "15:00"),
                            (18, "15:30"),
                            (19, "16:00"),
                            (20, "16:30"),
                            (21, "17:00"),
                            (22, "17:30"),
                            (23, "18:00"),
                            (24, "18:30"),
                        ],
                        verbose_name="Слот",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("start", "start"), ("busy", "busy"), ("free", "free")], verbose_name="Статус слота"
                    ),
                ),
                (
                    "previous_slot",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_slot",
                        to="services.slot",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="services.schedule",
                        verbose_name="Расписание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слот",
                "verbose_name_plural": "Слоты",
                "ordering": ["date", "number"],
                "unique_together": {("schedule", "number")},
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("appointment_date", models.DateField(verbose_name="Дата приема")),
                ("appointment_time", models.TimeField(verbose_name="Время приема")),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "status",
                    models.CharField(
                        choices=[("scheduled", "Запланирован"), ("completed", "Завершен"), ("cancelled", "Отменен")],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="users.doctor",
                        verbose_name="Врач",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пациент",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="services.service",
                        verbose_name="Услуга",
                    ),
                ),
                (
                    "slot",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointment",
                        to="services.slot",
                        verbose_name="Слот",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись на прием",
                "verbose_name_plural": "Записи на прием",
                "ordering": ["-date", "appointment_date", "appointment_time"],
            },
        ),
    ]
