# Generated by Django 5.2 on 2025-05-06 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="number",
            field=models.IntegerField(
                choices=[
                    (1, "07:00"),
                    (2, "07:30"),
                    (3, "08:00"),
                    (4, "08:30"),
                    (5, "09:00"),
                    (6, "09:30"),
                    (7, "10:00"),
                    (8, "10:30"),
                    (9, "11:00"),
                    (10, "11:30"),
                    (11, "12:00"),
                    (12, "12:30"),
                    (13, "13:00"),
                    (14, "13:30"),
                    (15, "14:00"),
                    (16, "14:30"),
                    (17, "15:00"),
                    (18, "15:30"),
                    (19, "16:00"),
                    (20, "16:30"),
                    (21, "17:00"),
                    (22, "17:30"),
                    (23, "18:00"),
                    (24, "18:30"),
                ],
                verbose_name="Слот",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="previous_slot",
            field=models.OneToOneField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_slot",
                to="services.slot",
            ),
        ),
    ]
