# Generated by Django 5.2 on 2025-05-06 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_slot_number_alter_slot_previous_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="slot",
            field=models.OneToOneField(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointment",
                to="services.slot",
                verbose_name="Слот",
            ),
        ),
    ]
