# Generated by Django 5.2 on 2025-05-07 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_alter_appointment_slot"),
        ("users", "0003_doctor_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryCoefficient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("highest", "Высшая"),
                            ("first", "Первая"),
                            ("second", "Вторая"),
                            ("none", "Нет категории"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Категория",
                    ),
                ),
                ("coefficient", models.DecimalField(decimal_places=2, max_digits=3, verbose_name="Коэффициент")),
            ],
            options={
                "verbose_name": "Коэффициент категории",
                "verbose_name_plural": "Коэффициенты категорий",
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="cost",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10, verbose_name="Стоимость"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="doctors",
            field=models.ManyToManyField(blank=True, related_name="services", to="users.doctor", verbose_name="Врачи"),
        ),
        migrations.AlterField(
            model_name="service",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="users.department",
                verbose_name="Отделение",
            ),
        ),
    ]
