# Generated by Django 5.2 on 2025-05-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_categorycoefficient_appointment_cost_service_doctors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorycoefficient",
            name="category",
            field=models.CharField(
                choices=[("highest", "Высшая"), ("first", "Первая"), ("second", "Вторая"), (None, "Нет категории")],
                max_length=20,
                unique=True,
                verbose_name="Категория",
            ),
        ),
    ]
