# Generated by Django 5.2 on 2025-05-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_alter_categorycoefficient_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorycoefficient",
            name="category",
            field=models.CharField(
                choices=[
                    ("first", "Первая категория"),
                    ("second", "Вторая категория"),
                    ("highest", "Высшая категория"),
                    ("none", "Нет категории"),
                ],
                default="none",
                max_length=20,
                unique=True,
                verbose_name="Категория",
            ),
        ),
    ]
