# Generated by Django 5.2 on 2025-05-07 09:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_alter_categorycoefficient_category"),
        ("users", "0006_alter_doctor_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorycoefficient",
            name="category",
            field=models.CharField(
                choices=[
                    ("none", "Нет категории"),
                    ("second", "Вторая категория"),
                    ("first", "Первая категория"),
                    ("highest", "Высшая категория"),
                ],
                default="none",
                max_length=20,
                unique=True,
                verbose_name="Категория",
            ),
        ),
        migrations.CreateModel(
            name="DiagnosticResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("diagnosis", models.TextField(verbose_name="Диагноз")),
                ("recommendations", models.TextField(verbose_name="Рекомендации")),
                ("medications", models.TextField(verbose_name="Назначенные лекарства")),
                (
                    "attachments",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="diagnostic_results/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="Прикрепленные файлы",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Ожидает заполнения"), ("completed", "Заполнено")],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnostic_result",
                        to="services.appointment",
                        verbose_name="Запись на прием",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnostic_results",
                        to="users.doctor",
                        verbose_name="Врач",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnostic_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат диагностики",
                "verbose_name_plural": "Результаты диагностики",
                "ordering": ["-created_at"],
            },
        ),
    ]
