# Generated by Django 5.2 on 2025-05-07 11:27

import django.core.validators
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_alter_categorycoefficient_category_diagnosticresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosticresult",
            name="attachments",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=services.models.get_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=["pdf", "jpg", "jpeg", "png"])
                ],
                verbose_name="Прикрепленные файлы",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosticresult",
            name="diagnosis",
            field=models.TextField(blank=True, null=True, verbose_name="Диагноз"),
        ),
        migrations.AlterField(
            model_name="diagnosticresult",
            name="medications",
            field=models.TextField(blank=True, null=True, verbose_name="Назначенные лекарства"),
        ),
        migrations.AlterField(
            model_name="diagnosticresult",
            name="recommendations",
            field=models.TextField(blank=True, null=True, verbose_name="Рекомендации"),
        ),
    ]
