# Generated by Django 5.2 on 2025-05-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0009_alter_appointment_options_appointment_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="payment_status",
            field=models.BooleanField(default=False, help_text="Статус оплаты приема", verbose_name="Оплата"),
        ),
    ]
