# Generated by Django 5.2 on 2025-05-07 13:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0010_alter_appointment_payment_status"),
        ("users", "0008_alter_department_description_alter_department_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Рейтинг услуги по отзывам пациентов (от 0 до 5)",
                max_digits=3,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)],
                verbose_name="Рейтинг",
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(help_text="Содержание отзыва", verbose_name="Текст отзыва")),
                (
                    "doctor_rating",
                    models.IntegerField(
                        default=0,
                        help_text="Оценка работы врача от 0 до 5",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Оценка врача",
                    ),
                ),
                (
                    "service_rating",
                    models.IntegerField(
                        default=0,
                        help_text="Оценка качества услуги от 0 до 5",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Оценка услуги",
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False, help_text="Отметка об анонимности отзыва", verbose_name="Анонимный отзыв"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Дата создания отзыва", verbose_name="Дата создания"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Врач, о котором оставлен отзыв",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="users.doctor",
                        verbose_name="Врач",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        help_text="Услуга, о которой оставлен отзыв",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="services.service",
                        verbose_name="Услуга",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пациент, который оставил отзыв",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-date"],
            },
        ),
    ]
