# Generated by Django 5.2 on 2025-05-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0011_service_rating_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(blank=True, help_text="Содержание отзыва", null=True, verbose_name="Текст отзыва"),
        ),
    ]
